-- Create tenant_common schema for MDM service
CREATE SCHEMA IF NOT EXISTS tenant_common;

-- Grant permissions
GRANT USAGE ON SCHEMA tenant_common TO PUBLIC;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA tenant_common TO PUBLIC;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA tenant_common TO PUBLIC;

-- Set default privileges for future tables
ALTER DEFAULT PRIVILEGES IN SCHEMA tenant_common GRANT ALL ON TABLES TO PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA tenant_common GRANT ALL ON SEQUENCES TO PUBLIC;
