-- Create hr_attendance schema
CREATE SCHEMA IF NOT EXISTS hr_attendance;

-- Grant permissions
GRANT USAGE ON SCHEMA hr_attendance TO PUBLIC;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA hr_attendance TO PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA hr_attendance GRANT ALL PRIVILEGES ON TABLES TO PUBLIC;
