CREATE SCHEMA IF NOT EXISTS hr_recruitment;
GRANT USAGE ON SCHEMA hr_recruitment TO PUBLIC;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA hr_recruitment TO PUBLIC;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA hr_recruitment TO PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA hr_recruitment GRANT ALL ON TABLES TO PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA hr_recruitment GRANT ALL ON SEQUENCES TO PUBLIC;
