-- Create hr_notification schema
CREATE SCHEMA IF NOT EXISTS hr_notification;

-- Grant permissions
GRANT USAGE ON SCHEMA hr_notification TO PUBLIC;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA hr_notification TO PUBLIC;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA hr_notification TO PUBLIC;

-- Set default privileges for future tables
ALTER DEFAULT PRIVILEGES IN SCHEMA hr_notification GRANT ALL ON TABLES TO PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA hr_notification GRANT ALL ON SEQUENCES TO PUBLIC;
