CREATE SCHEMA IF NOT EXISTS hr_appointment;
GRANT USAGE ON SCHEMA hr_appointment TO PUBLIC;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA hr_appointment TO PUBLIC;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA hr_appointment TO PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA hr_appointment GRANT ALL ON TABLES TO PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA hr_appointment GRANT ALL ON SEQUENCES TO PUBLIC;
