-- Create hr_core schema for organization service
CREATE SCHEMA IF NOT EXISTS hr_core;

-- Grant permissions
GRANT USAGE ON SCHEMA hr_core TO PUBLIC;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA hr_core TO PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA hr_core GRANT ALL PRIVILEGES ON TABLES TO PUBLIC;
