CREATE SCHEMA IF NOT EXISTS hr_certificate;
GRANT USAGE ON SCHEMA hr_certificate TO PUBLIC;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA hr_certificate TO PUBLIC;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA hr_certificate TO PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA hr_certificate GRANT ALL ON TABLES TO PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA hr_certificate GRANT ALL ON SEQUENCES TO PUBLIC;
