-- Create hr_file schema
CREATE SCHEMA IF NOT EXISTS hr_file;

GRANT USAGE ON SCHEMA hr_file TO PUBLIC;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA hr_file TO PUBLIC;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA hr_file TO PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA hr_file GRANT ALL ON TABLES TO PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA hr_file GRANT ALL ON SEQUENCES TO PUBLIC;
