-- Create hr_approval schema
CREATE SCHEMA IF NOT EXISTS hr_approval;

-- Grant permissions
GRANT USAGE ON SCHEMA hr_approval TO PUBLIC;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA hr_approval TO PUBLIC;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA hr_approval TO PUBLIC;

-- Set default privileges for future tables
ALTER DEFAULT PRIVILEGES IN SCHEMA hr_approval GRANT ALL ON TABLES TO PUBLIC;
ALTER DEFAULT PRIVILEGES IN SCHEMA hr_approval GRANT ALL ON SEQUENCES TO PUBLIC;
